<?php
/** @var Aoe_Static_Block_Beforebodyend $this */

$phoneCallUrl = Mage::getUrl(
    'phone/call/index',
    Mage::app()->getStore()->isCurrentlySecure() ? array('_secure' => 1) : array()
);

$currentProductId = ($_product = Mage::registry('product')) == true ?
    $_product->getId() :
    "null";

?>
<script type="text/javascript">

    var ajaxHomeCall = Object.create(ajaxHomeCallPrototype, {
        ajaxHomeUrl: {
            value: '<?php echo $phoneCallUrl; ?>'
        },
        fullActionName: {
            value: '<?php echo $this->getAction()->getFullActionName() ?>'
        },
        customerName: {
            value: '<?php echo $this->getCustomerName() ?>'
        },
        useSessionStorage: {
            value: <?php echo $this->useSessionStorage() ? "true" : "false" ?>
        },
        currentProductId: {
            value: <?php echo $currentProductId; ?>
        },
        cartSummaryCount: {
            value: '<?php echo $this->getCartSummaryCount(); ?>'
        },
        sessionStorageBlocks: {
            value: <?php echo $this->getSessionStorageBlocks(); ?>
        },
        sessionStorageGroups: {
            value: <?php echo $this->getSessionStorageGroups(); ?>
        }
    }).init();

</script>
